### ISSUE TITLE
My Angry Birds 

### ISSUE THREAD

**Issue by chaplyginmd** [chaplyginmd/AiSD2022#1]
Added a new project with the Bird class and a window that uses this class.

**Comment by justjune** [comment]
Не скопировались файл решения и файл проекта

**Comment by justjune** [comment]
Не увидел создание окна-сообщения, в обработчике вашего пользовательского события о столкновении.

**Comment by chaplyginmd** [comment]
Я его сделал на нажатие кнопки в файле ABPWindowClass

**Comment by justjune** [comment]
Там нет вызова обработчика: есть просто вызов функции.

**Comment by chaplyginmd** [comment]
Исправил обработчик события - столкновения: теперь при нажатии на кнопку, если случилось столкновение, то отображается окно - сообщение о столкновении; если такового не произошло, то пишет что не было столкновения.
Возможно, Вы это имели ввиду
